services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: legwor
      POSTGRES_PASSWORD: legwor
      POSTGRES_DB: legwor
    ports:
      - '5432:5432'
    volumes:
      - legwor_pg_data:/var/lib/postgresql/data

volumes:
  legwor_pg_data:
